---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rackspace-system

resources:
    - '../../../../mpk-apps/ceph-csi/'
    - './encrypted-secret.yaml'
    - './storageclass.yaml'

patchesStrategicMerge:
    - './configmap.yaml'
