---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rackspace-system

resources:
    - '../../../../mpk-apps/harbor-operator/'

patchesStrategicMerge:
    - './certificate.yaml'
    - './mutatingwebhookconfiguration.yaml'
    - './validatingwebhookconfiguration.yaml'
    - './crds.yaml'
