apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: velero
spec:
  encryptedData:
    cloud: AgAIJPuI69N3vAtHDCtCET1eO2qUvzS89+bTSI1I9dLyqe6lBkMb+CWsKrnk07a3BbsAoWihtTKE60AdaB5BUVrqDdH22yfG/xszDCKZHWfSj3R7u8LQCRVkdRU8TfqYqqpbyg/x5l6MmGIbUhdeou7MNPUQSfzq50lf1TURsrUmXWd64z+NUDLMwYfRCkjZ0dUyzbtzUJVXYJ9yoTwXHM80JbsjNkutpK9I/EhbqeGJ2JZWdEk2yHyWTctiR7x+f2lJLLm0OH1iGc1VdeM/+S8mQaGs5LAVQAkuos5ocND5jMNVP531cRyIccNdwNQ7oaBiaZyF+i97plAnqyku01ux3jkwosajdiNrCGKH95GmZFAWrXIaJaCH5caZxTiXa2JVNF1peDQGdiXxp0fpiTMw7OFPn5jNmCvAh7apPc1D/w1rcx6oUSNv0YIwdqfvHVQqQe6fWUOO6F5V30mvFXvyzZLNY8dlY+0LuGDCqROaNtFSMZ2NTYaxNLXkZFbfJ+cLb2014MBHq8IYBsHWYakR+geRdJ0a14a13znEByIxJwW74UHJZ9jchx+jXVFun01wJ5hCnKnRpJH7Yk5EK3lhbiCwb+tgBVFVJeHaeFPoeUX7lSSjnQVIpCRp+/VPCEVsU2vC9Mu7EJT1pDf2AJAFmG3WCeMSvgPO3WvU7H7TR0kGMg3iEQ95SaXdM6F5xY/+amf8jTgDj28mXW9WiMViIo/9PTJlKsM7v8dkaAfQJ2C5dJgNkSnU0Sz/uf4mFsD/TpLrj1TJ/my0i+PPnUEJBxol5BIp1Bx8l8SDsm1MMEPaLJROuPv74THw1UmwWyXKn9uZeDk4zmR127mxSzuVDMotulplJRLVIp0vaTyyqGVbP9JPx/CGnK0tpx+XfAL1LJqeNCLMGMO8Mso=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: velero
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: velero
        helm.sh/chart: velero-2.27.0
      name: velero
    type: Opaque

