apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: velero
spec:
  encryptedData:
    cloud: AgAkd300ifnn7qgK2NH6eBaAUGvphLrNnCL/F8xOZmwGCRt6x0j4JWmSOriTgzsUJBUKwU8wDfrAMA0VdXwa2wenob1d8SdHSMPSwCssT5mxTc4CRyX7OdjYPIkuHE2EBdwzNBNhq/b5VL0zK+HkKQiicDJzzgCtNvB0lYqRhJgX5itTOQAS2aJXtXBJtJVSJHgCXXFIKXdt20sOkYYGZaVNqVy0Hxzu9FQi/KZ5qAp7wzN23cCFrNLwnLZhlQqQa5CCb0tieNHqkaDmzhlgwB9IOECqpLEaK5mtumOmZ54JqyndRRBLyLOS47rvrtKbHNiQhnwUgDUHWBI29rk89o3PvzVBmfesdFQNol7bEydhN5WdoVZsUXYf+WGbJ3Pvowytf28tPc0Xi9q9nkbE2bWjRaWFqsdeSxj4Oe+1QghZgTj+slBbZcHws0SnaWKITKmALt5drD8FIf9fScjAIYPU1ZCTCXDqukQ1hSYUeQ6jeI6EsX06X3fqtpeUnbXtQGg6VCTBe/5WAgOH9VDdSPXvLWCv7m/3GwYEjEP8clqEIv3bay5jTghDu24LcTAspbpvke1xcagocbi1a3x3ZkNsBFI7bpLp9B5cRk3JlYMaxiMsyYDWhrYHnK+guG4r5nJDLhuv1Y39fjd/+4n9NpzrUChsTYp3LE70VT0TpjUeBkqGenKSuAm5zaz2Ekv61Ybg9XpVezMb/nm/GPhXazwl9hjDHY1d/ZSLlzqkXJ+rY31hpYncleVsHhsv8qeQYUFaujQrUUNEDLI+mx+nWjS3EdE+KFiLbTZ5ZUqsJZhHKbLSimjZMHJYb+4g49wZ8+MkvGia9Fwr+4jfyktQDpNzBrT5KzIS/0t1iKq59KKR+2sbGRm4VTKpOheYDVVw0pKNJipKPdqVC5js1Fc=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: velero
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: velero
        helm.sh/chart: velero-2.27.0
      name: velero
    type: Opaque

