---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alpha-rke-cluster-external-snapshotter
  namespace: argocd
  labels:
    env: alpha-rke-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: alpha-rke-cluster
  source:
    repoURL: https://github.com/vish6760/alpha-managed-services.git
    path: alpha-rke-cluster/overlays/rackspace-system/external-snapshotter
    targetRevision: HEAD

  destination:
    name: in-cluster

  syncPolicy:
    automated:
      selfHeal: true
      prune: true

