---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rackspace-system

resources:
    - '../../../../mpk-apps/ingress-nginx/'

patchesStrategicMerge:
    - './ingressclass.yaml'
