---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rackspace-system

resources:
    - '../../../../mpk-apps/cert-manager/'
    - './encrypted-route53-secret.yaml'
    - './route53-cluster-issuer.yaml'

patchesStrategicMerge:
    - './crds.yaml'
    - './deployment.yaml'
    - './webhook.yaml'
