apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: external-dns
spec:
  encryptedData:
    credentials: AgAV32rp8XlqosLhfFwaOJD/8uIYQlBCl3GPDefQA2ij98DDI+e5Ec4gJEanmJkqISDyxN20DgVetaxc6SS1v8FNvh93mcrmAiTeT/Uh+52gwiwsHWp3UCvTKmYHQG0js+HQnOnMJsl12ld+AzFK8Bh01+yUZexfyh2QAWoH9t2SqrDBn0iwBgDdH8IPPQJJwvPmrb+08JY2iYFDzmtUm1xHElb9YWuY5fGipHbSf+pop0e0LuBOKbMTuZNFRljoX5q/2kGEORs2GbpiXYk9zj+dfguBvRaZgqtsm3pDVKYgbIA/8X0vM2x4Wlg8h2VOW6qxXE4LF3/Karc4B3Ewt2uO4iGIIAmbO/m2KExh7IuwbZGRS9aZ079by4mVPcwYFt0XNuA0HaHngImbVl1D5cLKBYHlhFkgxQxSlU5ZTb4bXshmEa8E0e7TW/gB0x8aF+Pu1Mn5JA94veJB89USRw4Be1QThCvZnFsWdlNdDEsgVsFsD0d8XMdW7/+GebqoKkqd1orDLT8FC11CvNRoJAjU2ty3F33Pf2CF8HNmojE9VgsNpg73s1nlbkB35d+3qR3JPNZpPWoPgqLhg48C1mDbjL+7c5nMTugNiQonjdEfVGR21V7u8IsUGFiIKPcUT4l/SRyA1cmOZa9BWlgVx1pALGYWTBWcZ4UgEWel2vsw5A4X8VTuFcu0yk4Sq0VI/Z9683mdyXxcMZNWqHYwVfeMqb5ffOf+xATDl+OvE3Csxe+Wd7yQKYbPhYjV71BMkhok8LkjA1xCb6KPnZ80zIVLmHN4VzqGyBu6IrSlf3K8HBKz+tg0WkOTmgvsUg5PTiGOrDVfFv+qS1I+ry8dA7f6AJgST25yxj3sd+/m9ssWQAbOOsKHIeb8LTy59W2aGtPziU+ghzfJPqP/rx8=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: external-dns
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: external-dns
        helm.sh/chart: external-dns-5.4.11
      name: external-dns
    type: Opaque

