apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: external-dns
spec:
  encryptedData:
    credentials: AgBTLZoOVB5EWi2cDjBH7fLJhs79QQJaN0nj8RtQwLUcHaKe5VTwdc26OQSSfaYhlPmCqVOtN6+bEOp+PZ21hQlzjY4lETUp+Nd5PGTFO6O9qABiYfO69mwGMIT65MRYC9AEPpNU1oVQrBkQ1gTFLb/06JYPtkgGVhxU2TJR/37tnHtBTmmAMiRXtK5jKAOKL5SligqScsyl8/YnGPgHCWjy0wv1Wpqsoc1qaNKsvFGZW69Jrha8hnLKL6caJgl2Oz/uedTlBjQb6P5UHe0uwzUz8vh+jhYIVh/GtXMA2l5B+f7E3jIOE4opqL/g7Q9k0aSp1qqKEXCX8eZsMvttHT9RG7RHAft7AvJE6hFevSLfnFATMwXREvvj78nqyUi6exEWy1g9AcA7xrsG9DKZ2z2A0BGn61YyKcx/9E9HhWHmzYEiJGNo2wlP+1cLb8axN6rfKJGh+QDyyRzVXC9lfGIbkP7PhN9QMtWvUojKx6rk5jmUpwmrwwoven2ymAMVLJCwGWUlAQSiytojWYV5XB9vFg8CBJTjXgd/1rx6PAMovFIxSY7XIVLy8U9DbpmFsmGUlNXM9foRklXL+l1bB73PeL4ln+N9b1xhFFtnbMZ3zoOFHmSGwvw+m4+lg8GAnyG2/s3QdeaDhl8Ts4SVEfIfYzrfsS8zLKl5i1ZPapdlOe/CW5I9WDgi5oc4mIol2FR56QQDgbpWOKDG4UDPSwQx4S378+ShFwZVKkKh3yRrh6ad1Z0mbE6bEuke+dh4TMDLNlM7ICYUeYYHf6gRqJoWgWL28OiIzeOCM2tVZJLcoRRUsn+pDHDIwnZnwMMY9sQRXm6qbnZMArGyTp2ANb8ZznPaXdx8mG1VEX5VnslGG3s+qJ09cmcYcGtoZnsa9usHbGH8gQuZf3hHWjA=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: external-dns
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: external-dns
        helm.sh/chart: external-dns-5.4.11
      name: external-dns
    type: Opaque

