---
# Source: sealed-secrets/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: controller
          args:
            - --update-status
            - --key-prefix
            - "sealed-secrets-key"
            - --key-renew-period=0