---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - 'https://github.com/rackerlabs/mpk-apps.git/defaults/sealed-secrets'

patchesStrategicMerge:
    - './deployment.yaml'
