---
# Certificates of ingress
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-public-certificate
spec:
  secretName: harbor-public-certificate
  dnsNames:
    - harbor-alpha.demo.mk8s.net
    - notary-alpha.demo.mk8s.net
  issuerRef:
    name: route53-cluster-issuer
    kind: ClusterIssuer